export interface ItemBase {
  id: number;
  title: string;
  description: string;
  quantity?: number;
  yearPeriod?: string;
  image: string;
  images?: string[];
  valuation?: number;
  valuationDate?: string;
  valuationPerson?: string;
  valuationCurrency?: string;
  house?: string;
  room?: string;
  /**
   * Optional field from the API used to sort by location.
   * When present, it takes precedence over computed house/room order.
   */
  locationSort?: number | string;
  notes?: string;
  /**
   * Marks an item as deleted instead of removing it permanently.
   */
  deleted?: boolean;
}

export type CollectionType = 'art' | 'books' | 'music';

export interface DecorItem extends ItemBase {
  code?: string;
  artist?: string;
  originRegion?: string;
  category: string;
  subcategory?: string;
  material?: string;
  size?: string;
  widthCm?: number;
  heightCm?: number;
  depthCm?: number;
  weightKg?: number;
  provenance?: string;
  version?: number;
  condition: 'mint' | 'excellent' | 'very good' | 'good';
  acquisitionDate?: string;
  acquisitionValue?: number;
  acquisitionCurrency?: string;
  /**
   * Keeps previous versions of the item when edits occur.
   */
  history?: DecorItem[];
}

export interface BookItem extends ItemBase {
  author?: string;
  publisher?: string;
  isbn?: string;
  category?: string;
  subcategory?: string;
  genre?: string;
  pageCount?: number;
  publicationYear?: number;
  /**
   * Keeps previous versions of the item when edits occur.
   */
  history?: BookItem[];
}

export interface MusicItem extends ItemBase {
  artist?: string;
  album?: string;
  format?: string;
  category?: string;
  subcategory?: string;
  genre?: string;
  releaseYear?: number;
  trackCount?: number;
  /**
   * Keeps previous versions of the item when edits occur.
   */
  history?: MusicItem[];
}

export interface DecorItemInput {
  id?: number;
  code?: string;
  name: string;
  room_code: string;
  house?: string;
  room?: string;
  house_code?: string;
  creator: string;
  origin_region: string;
  date_period: string | number;
  material?: string;
  height_cm?: number;
  width_cm?: number;
  depth_cm?: number;
  weight_kg?: number;
  provenance?: string;
  category: string;
  subcategory: string;
  quantity: number;
  acquisition_date?: string;
  acquisition_value?: number;
  acquisition_currency?: string;
  appraisal_date?: string;
  appraisal_value?: number;
  appraisal_currency?: string;
  appraisal_entity?: string;
  description?: string;
  notes?: string;
  version?: number;
  is_deleted?: boolean;
}

export interface BookItemInput {
  id?: number;
  title: string;
  author?: string;
  publisher?: string;
  isbn?: string;
  category?: string;
  subcategory?: string;
  genre?: string;
  pageCount?: number;
  publicationYear?: number;
  quantity?: number;
  description?: string;
  notes?: string;
  house?: string;
  room?: string;
  valuation?: number;
  valuationCurrency?: string;
  valuationDate?: string;
  deleted?: boolean;
}

export interface MusicItemInput {
  id?: number;
  title: string;
  artist?: string;
  album?: string;
  format?: string;
  category?: string;
  subcategory?: string;
  genre?: string;
  releaseYear?: number;
  trackCount?: number;
  quantity?: number;
  description?: string;
  notes?: string;
  house?: string;
  room?: string;
  valuation?: number;
  valuationCurrency?: string;
  valuationDate?: string;
  deleted?: boolean;
}

export type InventoryItemInput =
  | DecorItemInput
  | BookItemInput
  | MusicItemInput;

export type InventoryItem = DecorItem | BookItem | MusicItem;

export type ViewMode = 'grid' | 'list' | 'table';
export type CategoryFilter = 'all' | string;
export type HouseFilter = 'all' | string;
export type RoomFilter = 'all' | string;

// Configuration types for settings
export interface CategoryConfig {
  id: string;
  name: string;
  icon: string;
  subcategories: SubcategoryConfig[];
  visible: boolean;
}

export interface SubcategoryConfig {
  id: string;
  name: string;
  visible: boolean;
}

export interface HouseConfig {
  id: string;
  code: string;
  name: string;
  address?: string;
  city: string;
  country: string;
  postal_code?: string;
  beneficiary?: string[];
  latitude?: number;
  longitude?: number;
  description?: string;
  notes?: string;
  icon: string;
  rooms: RoomConfig[];
  visible: boolean;
  version: number;
  is_deleted: boolean;
  history?: HouseConfig[];
}

export interface RoomConfig {
  id: string;
  /**
   * Generated by the backend as a sequential string based on the house code.
   */
  code?: string;
  name: string;
  house_code?: string;
  room_type?: string;
  floor: number;
  area_sqm?: number;
  windows?: number;
  doors?: number;
  description?: string;
  notes?: string;
  version: number;
  is_deleted: boolean;
  visible?: boolean;
  history?: RoomConfig[];
}

// Category configurations per collection
export const decorCategoryConfigs: CategoryConfig[] = [
  {
    id: 'art',
    name: 'Art',
    icon: 'palette',
    subcategories: [
      { id: 'painting', name: 'Painting', visible: true },
      { id: 'sculpture', name: 'Sculpture', visible: true },
      { id: 'photography', name: 'Photography', visible: true },
      { id: 'print', name: 'Print', visible: true },
    ],
    visible: true,
  },
  {
    id: 'furniture',
    name: 'Furniture',
    icon: 'sofa',
    subcategories: [
      { id: 'chair', name: 'Chair', visible: true },
      { id: 'table', name: 'Table', visible: true },
      { id: 'sofa', name: 'Sofa', visible: true },
      { id: 'cabinet', name: 'Cabinet', visible: true },
      { id: 'rug', name: 'Rug', visible: true },
    ],
    visible: true,
  },
  {
    id: 'decorative',
    name: 'Decorative',
    icon: 'lamp',
    subcategories: [
      { id: 'vase', name: 'Vase', visible: true },
      { id: 'basket', name: 'Basket', visible: true },
      { id: 'mirror', name: 'Mirror', visible: true },
      { id: 'lighting', name: 'Lighting', visible: true },
    ],
    visible: true,
  },
  {
    id: 'kitchenware',
    name: 'Kitchenware',
    icon: 'utensils',
    subcategories: [{ id: 'tea-set', name: 'Tea Set', visible: true }],
    visible: true,
  },
];

export const bookCategoryConfigs: CategoryConfig[] = [
  {
    id: 'fiction',
    name: 'Fiction',
    icon: 'book',
    subcategories: [
      { id: 'literary', name: 'Literary', visible: true },
      { id: 'mystery', name: 'Mystery', visible: true },
      { id: 'fantasy', name: 'Fantasy', visible: true },
      { id: 'historical', name: 'Historical', visible: true },
    ],
    visible: true,
  },
  {
    id: 'non-fiction',
    name: 'Non-Fiction',
    icon: 'library',
    subcategories: [
      { id: 'biography', name: 'Biography', visible: true },
      { id: 'history', name: 'History', visible: true },
      { id: 'science', name: 'Science', visible: true },
      { id: 'art-history', name: 'Art History', visible: true },
    ],
    visible: true,
  },
  {
    id: 'reference',
    name: 'Reference',
    icon: 'file-text',
    subcategories: [
      { id: 'encyclopedia', name: 'Encyclopedias', visible: true },
      { id: 'atlas', name: 'Atlases', visible: true },
      { id: 'catalogue', name: 'Catalogues', visible: true },
    ],
    visible: true,
  },
];

export const musicCategoryConfigs: CategoryConfig[] = [
  {
    id: 'recordings',
    name: 'Recordings',
    icon: 'disc',
    subcategories: [
      { id: 'vinyl', name: 'Vinyl', visible: true },
      { id: 'cd', name: 'CD', visible: true },
      { id: 'cassette', name: 'Cassette', visible: true },
    ],
    visible: true,
  },
  {
    id: 'scores',
    name: 'Scores & Sheet Music',
    icon: 'music',
    subcategories: [
      { id: 'orchestral', name: 'Orchestral', visible: true },
      { id: 'chamber', name: 'Chamber', visible: true },
      { id: 'vocal', name: 'Vocal', visible: true },
    ],
    visible: true,
  },
  {
    id: 'memorabilia',
    name: 'Memorabilia',
    icon: 'ticket',
    subcategories: [
      { id: 'posters', name: 'Posters', visible: true },
      { id: 'programs', name: 'Programs', visible: true },
      { id: 'merchandise', name: 'Merchandise', visible: true },
    ],
    visible: true,
  },
];

export const collectionCategoryConfigs: Record<
  CollectionType,
  CategoryConfig[]
> = {
  art: decorCategoryConfigs,
  books: bookCategoryConfigs,
  music: musicCategoryConfigs,
};

// House configurations per collection
export const decorDefaultHouses: HouseConfig[] = [
  {
    id: 'main-house',
    code: 'MH01',
    name: 'Main House',
    address: '123 Main Street, Beverly Hills, CA',
    city: 'Beverly Hills',
    country: 'United States',
    postal_code: '90210',
    beneficiary: ['Owner'],
    latitude: 34.0736,
    longitude: -118.4004,
    description: 'Primary residence',
    notes: '',
    version: 1,
    is_deleted: false,
    icon: 'house',
    rooms: [
      {
        id: 'living-room',
        name: 'Living Room',
        floor: 1,
        version: 1,
        is_deleted: false,
        visible: true,
      },
      {
        id: 'dining-room',
        name: 'Dining Room',
        floor: 1,
        version: 1,
        is_deleted: false,
        visible: true,
      },
      {
        id: 'kitchen',
        name: 'Kitchen',
        floor: 1,
        version: 1,
        is_deleted: false,
        visible: true,
      },
      {
        id: 'bedroom',
        name: 'Bedroom',
        floor: 2,
        version: 1,
        is_deleted: false,
        visible: true,
      },
      {
        id: 'office',
        name: 'Office',
        floor: 2,
        version: 1,
        is_deleted: false,
        visible: true,
      },
      {
        id: 'bathroom',
        name: 'Bathroom',
        floor: 2,
        version: 1,
        is_deleted: false,
        visible: true,
      },
      {
        id: 'hallway',
        name: 'Hallway',
        floor: 1,
        version: 1,
        is_deleted: false,
        visible: true,
      },
    ],
    visible: true,
  },
  {
    id: 'guest-house',
    code: 'GH01',
    name: 'Guest House',
    address: '125 Main Street, Beverly Hills, CA',
    city: 'Beverly Hills',
    country: 'United States',
    postal_code: '90210',
    beneficiary: ['Guests'],
    latitude: 34.0736,
    longitude: -118.4004,
    description: 'Guest accommodation',
    notes: '',
    version: 1,
    is_deleted: false,
    icon: 'house',
    rooms: [
      {
        id: 'living-room',
        name: 'Living Room',
        floor: 1,
        version: 1,
        is_deleted: false,
        visible: true,
      },
      {
        id: 'bedroom',
        name: 'Bedroom',
        floor: 1,
        version: 1,
        is_deleted: false,
        visible: true,
      },
      {
        id: 'kitchen',
        name: 'Kitchen',
        floor: 1,
        version: 1,
        is_deleted: false,
        visible: true,
      },
      {
        id: 'bathroom',
        name: 'Bathroom',
        floor: 1,
        version: 1,
        is_deleted: false,
        visible: true,
      },
    ],
    visible: true,
  },
  {
    id: 'studio',
    code: 'ST01',
    name: 'Studio',
    address: '45 Rue de Rivoli, Paris',
    city: 'Paris',
    country: 'France',
    postal_code: '75001',
    beneficiary: ['Artist'],
    latitude: 48.8559,
    longitude: 2.3601,
    description: 'Work studio',
    notes: '',
    version: 1,
    is_deleted: false,
    icon: 'house',
    rooms: [
      {
        id: 'main-area',
        name: 'Main Area',
        floor: 1,
        version: 1,
        is_deleted: false,
        visible: true,
      },
      {
        id: 'storage',
        name: 'Storage',
        floor: 1,
        version: 1,
        is_deleted: false,
        visible: true,
      },
    ],
    visible: true,
  },
];

export const bookDefaultHouses: HouseConfig[] = [
  {
    id: 'central-library',
    code: 'LIB01',
    name: 'Central Library',
    address: '12 Library Square, London',
    city: 'London',
    country: 'United Kingdom',
    postal_code: 'WC2N 5DU',
    beneficiary: ['Readers'],
    latitude: 51.5074,
    longitude: -0.1278,
    description: 'Primary reading room and public stacks',
    notes: '',
    version: 1,
    is_deleted: false,
    icon: 'library',
    rooms: [
      {
        id: 'reading-room',
        name: 'Reading Room',
        floor: 1,
        version: 1,
        is_deleted: false,
        visible: true,
      },
      {
        id: 'stacks',
        name: 'Main Stacks',
        floor: 2,
        version: 1,
        is_deleted: false,
        visible: true,
      },
      {
        id: 'children',
        name: "Children's Wing",
        floor: 1,
        version: 1,
        is_deleted: false,
        visible: true,
      },
    ],
    visible: true,
  },
  {
    id: 'research-archive',
    code: 'ARC01',
    name: 'Research Archive',
    address: '24 Scholar Lane, Oxford',
    city: 'Oxford',
    country: 'United Kingdom',
    postal_code: 'OX1 2JD',
    beneficiary: ['Researchers'],
    latitude: 51.752,
    longitude: -1.2577,
    description: 'Special collections and archives',
    notes: '',
    version: 1,
    is_deleted: false,
    icon: 'archive',
    rooms: [
      {
        id: 'rare-books',
        name: 'Rare Books Vault',
        floor: -1,
        version: 1,
        is_deleted: false,
        visible: true,
      },
      {
        id: 'manuscripts',
        name: 'Manuscripts Room',
        floor: 1,
        version: 1,
        is_deleted: false,
        visible: true,
      },
    ],
    visible: true,
  },
  {
    id: 'offsite-storage',
    code: 'STR01',
    name: 'Offsite Storage',
    address: '185 Archive Way, Cambridge',
    city: 'Cambridge',
    country: 'United Kingdom',
    postal_code: 'CB2 1TN',
    beneficiary: ['Collection'],
    latitude: 52.2053,
    longitude: 0.1218,
    description: 'Climate controlled storage',
    notes: '',
    version: 1,
    is_deleted: false,
    icon: 'warehouse',
    rooms: [
      {
        id: 'compact-storage',
        name: 'Compact Storage',
        floor: 1,
        version: 1,
        is_deleted: false,
        visible: true,
      },
      {
        id: 'oversized',
        name: 'Oversized Items',
        floor: 1,
        version: 1,
        is_deleted: false,
        visible: true,
      },
    ],
    visible: true,
  },
];

export const musicDefaultHouses: HouseConfig[] = [
  {
    id: 'music-vault',
    code: 'MV01',
    name: 'Music Vault',
    address: '500 Harmony Ave, Nashville, TN',
    city: 'Nashville',
    country: 'United States',
    postal_code: '37201',
    beneficiary: ['Archive'],
    latitude: 36.1627,
    longitude: -86.7816,
    description: 'Secured vault for master recordings',
    notes: '',
    version: 1,
    is_deleted: false,
    icon: 'vault',
    rooms: [
      {
        id: 'vinyl-room',
        name: 'Vinyl Room',
        floor: 1,
        version: 1,
        is_deleted: false,
        visible: true,
      },
      {
        id: 'master-tapes',
        name: 'Master Tapes',
        floor: -1,
        version: 1,
        is_deleted: false,
        visible: true,
      },
    ],
    visible: true,
  },
  {
    id: 'recording-studio',
    code: 'STU01',
    name: 'Recording Studio',
    address: '215 Rhythm Rd, Los Angeles, CA',
    city: 'Los Angeles',
    country: 'United States',
    postal_code: '90028',
    beneficiary: ['Artists'],
    latitude: 34.0522,
    longitude: -118.2437,
    description: 'Active studio and production spaces',
    notes: '',
    version: 1,
    is_deleted: false,
    icon: 'audio-lines',
    rooms: [
      {
        id: 'control-room',
        name: 'Control Room',
        floor: 1,
        version: 1,
        is_deleted: false,
        visible: true,
      },
      {
        id: 'live-room',
        name: 'Live Room',
        floor: 1,
        version: 1,
        is_deleted: false,
        visible: true,
      },
    ],
    visible: true,
  },
  {
    id: 'listening-lounge',
    code: 'LL01',
    name: 'Listening Lounge',
    address: '88 Melody St, New York, NY',
    city: 'New York',
    country: 'United States',
    postal_code: '10012',
    beneficiary: ['Guests'],
    latitude: 40.7265,
    longitude: -73.9987,
    description: 'Dedicated listening and event space',
    notes: '',
    version: 1,
    is_deleted: false,
    icon: 'headphones',
    rooms: [
      {
        id: 'main-lounge',
        name: 'Main Lounge',
        floor: 1,
        version: 1,
        is_deleted: false,
        visible: true,
      },
      {
        id: 'private-suite',
        name: 'Private Suite',
        floor: 2,
        version: 1,
        is_deleted: false,
        visible: true,
      },
    ],
    visible: true,
  },
];

export const collectionDefaultHouses: Record<
  CollectionType,
  HouseConfig[]
> = {
  art: decorDefaultHouses,
  books: bookDefaultHouses,
  music: musicDefaultHouses,
};
